export const quotes = [
    "Limba este întâiul mare poem al unui popor. Lucian Blaga",
"Prin arborele nostru genealogic, crescut din altoirea mlădiţei latine pe trunchiul dacic, curge seva limbii române. Suntem români prin datul sorţii, din porunca rădăcinii. Iar ramul care îşi reneagă rădăcina este sortit pieirii. Arcadie Suceveanu",
"Limba română este patria mea. De aceea, pentru mine, muntele munte se numeşte, de aceea, pentru mine, iarba iarbă se spune, de aceea, pentru mine, izvorul izvorăşte, de aceea, pentru mine, viaţa se trăieşte. Nichita Stănescu",
"Întotdeauna m-am mirat cum poţi să rămâi un prost în mijlocul unei Limbi atât de frumoase şi înţelepte cum este Limba Română? Grigore Vieru",
"Câtă limbă română a rămas în Basarabia, ar putea s-o înveţe uşor şi rusul. Grigore Vieru",
"Limba noastră-i o comoară, /Eu zic să o păzim, flăcăi, /Că astăzi pe diverse căi /Vin unii şi o... omoară! David Boia",
"Am văzut Limba Română ca pe-o mireasă: intangibil de fatală! Costel Zăgan",
"Câtă limbă română a rămas în Basarabia, ar putea s-o înveţe uşor şi rusul. Grigore Vieru",
"Pentru mine, limba română e distanţa dintre inimă şi umbra ei, care se numeşte suflet. Fănuș Neagu",
"Trăiască frumoasa şi cumintea limbă română! Fie în veci păstrată cu sfinţenie această scumpă Carte-de-boierie a unui neam călit la focul atâtor încercări de pierzanie. Ion Luca Caragiale",
"Limba română la sine acasă e o împărăţie bogată, căreia multe popoare i-au plătit banii în aur. A o dezbrăca de averile pe care ea le-a adunat în mai bine de 1000 de ani, înseamnă a o face din împărăteasă cerşetoare... Mihai Eminescu",
"S-ar putea crede că întreaga natură a ostenit la zidirea Limbii Române. Grigore Vieru",
"Orice ar fi, pasiune sau dorinţă, sete sau foame de experienţă reală, toate acestea se pot exprima în limba română prin cuvântul dor, care a devenit expresia oricărei dorinţe şi care implică fiinţa umană în totalitatea sa. Mircea Eliade",
"A vorbi despre limba română este ca o duminică. Limba română este patria mea. De aceea, pentru mine, muntele munte se numeşte, de aceea, pentru mine, iarba iarbă se spune, de aceea, pentru mine, izvorul izvorăşte, de aceea, pentru mine, viaţa se trăieşte. Nichita Stănescu",
"Limba este însăși floarea sufletului etnic al românimii. Mihai Eminescu",
"La români limba este parcă mai aproape de dinţi decât la alţii. Grigore Vieru",
"Limba este cartea de noblețe a unui neam. Vasile Alecsandri",
"Orice ar fi, pasiune sau dorință, sete sau foame de experiență reală, toate acestea se pot exprima în limba română prin cuvântul dor, care a devenit expresia oricărei dorințe și care implică ființa umană în totalitatea sa. Mircea Eliade",
"Limba română are virtuți complete, adică poate fi vehicol a tot ce se întâmplă spiritual în om. E foarte greu de mânuit. Prin ea poți deveni vultur sau cântăreţ de strană. Limba română are toate premisele valorice pentru a deveni o limbă universală, dar nu ştiu dacă e posibil acest marş istoric. Dacă am fi fost un popor cuceritor… Noi, românii, nu punctăm universalitatea nicăieri. Şi asta ne face sceptici. Ceea ce ne lipseşte este îndrăzneala. Petre Ţuţea",
"Limba română la sine acasă e o împărăţie bogată, căreia multe popoare i-au plătit banii în aur. A o dezbrăca de averile pe care ea le-a adunat în mai bine de 1000 de ani, înseamnă a o face din împărăteasă cerşetoare…  Mihai Eminescu",
"Să treci de la limba română la limba franceză e ca şi cum ai trece de la o rugăciune la un contract. Emil Cioran",
"Am fost mereu uimită de varietatea lingvistică a limbii române, de metaforele pe care le conţine. E o altă dimensiune a sinelui, pe care ţi-o conferă, de parcă aş avea două staţii, una a limbii pe care o întrebuinţez, alta, cea oferită de cuvântul echivalent al celeilalte limbi, care oferă o altă imagine. Limba română mă însoţeşte permanent, o am în cap, chiar dacă scriu în limba germană. Mă însoţesc, întotdeauna, în paralel, imaginile celeilalte limbi. Herta Muller",
"Trăiască frumoasa şi cumintea limbă română! Fie în veci păstrată cu sfinţenie această scumpă Carte-de-boierie a unui neam călit la focul atâtor încercări de pierzanie. Ion Luca Caragiale",
"Ceea ce nu piere, oricât de pieritoare ar fi întâmplările vieţii noastre, e gândul însuşi că le-am trăit, e limba în care s-a întrupat acest gând. Constantin Dumitru",
"Limba românească, căreia i se închinară părinţii noştri ca unui idol viu şi însufleţitor, e singurul tezaur ce ne-a rămas de la ei, ereditate neînstrăinată şi necomună cu alţii. Timotei Cipariu",
"Limba română e actul meu de naştere, eu sunt fiinţă sub  măslinul ei, care rodeşte de două mii de ani, dreptul meu e să-i ţin dealul verde şi bătut de soare şi să stau în genunchi sub ploaia cântecelor ce ţâşnesc din ea. Fănuş Neagu",
"Limba Română este o limbă extremă: când o vorbeşti pare că nu există, când taci, încep s-o vorbească toate lucrurile. Costel Zăgan",
"N-aş fi abandonat nicicând limba noastră; mi se întâmplă să-i regret şi acum mirosul de prospeţime şi putreziciune, amestecul de soare şi bălegar, urâţenia nostalgică şi superba neglijenţă. Emil Cioran",
"Limba română are virtuţi complete, adică poate fi vehicol a tot ce se întâmplă spiritual în om. E foarte greu de mânuit. Prin ea poţi deveni vultur sau cântăreţ de strană. Limba română are toate premisele valorice pentru a deveni o limbă universală, dar nu ştiu dacă e posibil acest marş istoric. Petre Țuțea",
"Oricât am fi de buni sau răi vreodată oricât am fi de falşi sau de fireşti ne regăsim sfioşi cu toţii, iată în templul limbii noastre româneşti. Corneliu Vadim Tudor",
"Cu cât scriu mai mult în franceză, cu atât mă fascinează mai mult limba română. De câte ori reîncep să scriu în limba română, redescopăr muzicalitatea limbii materne. Mă fascinează argoul jurnalistic, mă fascinează etajele argotice ale societăţii de consum. Matei Vișniec"
]